<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceEntitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Categorías principales
        $categories = [
            [
                'name' => 'Servicios Básicos',
                'description' => 'Servicios esenciales como agua, luz, gas y alcantarillado.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Servicios de Comunicación y Entretenimiento',
                'description' => 'Servicios de comunicación y entretenimiento, como internet, telefonía y streaming.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gastos de Vivienda',
                'description' => 'Pagos relacionados con vivienda, como alquiler, hipotecas y seguros.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Préstamos y Créditos',
                'description' => 'Pagos relacionados con préstamos personales, créditos y deudas.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seguros',
                'description' => 'Pagos relacionados con diferentes tipos de seguros.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Impuestos y Obligaciones Legales',
                'description' => 'Pagos de impuestos, contribuciones y obligaciones legales.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gastos Médicos y de Salud',
                'description' => 'Pagos relacionados con atención médica, tratamientos y medicamentos.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Educación',
                'description' => 'Pagos relacionados con educación como colegiaturas, matrículas y cursos.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Transporte y Movilidad',
                'description' => 'Pagos relacionados con transporte público, mantenimiento de vehículos y movilidad.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hobbies y Membresías',
                'description' => 'Pagos relacionados con actividades recreativas, clubes y membresías.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pagos Recurrentes Específicos',
                'description' => 'Pagos periódicos por servicios específicos como software, equipos o servicios domésticos.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Otros Servicios Financieros',
                'description' => 'Pagos relacionados con ahorro, inversiones y otras obligaciones financieras.',
                'parent_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $services = [
            // Servicios Básicos
            [
                'name' => 'Recibo de luz',
                'description' => 'Pago mensual del suministro de electricidad.',
                'parent_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recibo de agua',
                'description' => 'Pago mensual del suministro de agua.',
                'parent_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recibo de gas',
                'description' => 'Pago mensual del suministro de gas domiciliario.',
                'parent_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Servicio de alcantarillado',
                'description' => 'Pago por el uso del servicio de alcantarillado.',
                'parent_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Servicios de Comunicación y Entretenimiento
            [
                'name' => 'Suscripción a internet',
                'description' => 'Pago mensual por el servicio de internet.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a teléfono móvil',
                'description' => 'Pago mensual por el servicio de telefonía móvil.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a televisión por cable',
                'description' => 'Pago mensual por el servicio de televisión por cable.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a Netflix',
                'description' => 'Pago mensual por el servicio de streaming de Netflix.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a Spotify',
                'description' => 'Pago mensual por el servicio de música en streaming de Spotify.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a Disney+',
                'description' => 'Pago mensual por el servicio de streaming de Disney+.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a Amazon Prime',
                'description' => 'Pago mensual por el servicio de streaming de Amazon Prime.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a Apple TV+',
                'description' => 'Pago mensual por el servicio de streaming de Apple TV+.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a HBO Max',
                'description' => 'Pago mensual por el servicio de streaming de HBO Max.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a YouTube Premium',
                'description' => 'Pago mensual por el servicio sin anuncios de YouTube Premium.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Otra suscripción',
                'description' => 'Cualquier otro tipo de suscripción recurrente.',
                'parent_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Gastos de Vivienda
            [
                'name' => 'Pago de alquiler',
                'description' => 'Pago mensual por el alquiler de una vivienda o local.',
                'parent_id' => 3,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de hipoteca',
                'description' => 'Pago mensual de una hipoteca de vivienda.',
                'parent_id' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cuota de mantenimiento de condominio',
                'description' => 'Pago recurrente por servicios y mantenimiento de un condominio.',
                'parent_id' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seguro de vivienda',
                'description' => 'Pago mensual o anual del seguro de vivienda.',
                'parent_id' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Préstamos y Créditos
            [
                'name' => 'Préstamo personal',
                'description' => 'Pago recurrente de cuotas de un préstamo personal.',
                'parent_id' => 4,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crédito hipotecario',
                'description' => 'Pago mensual de un crédito hipotecario.',
                'parent_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crédito automotriz',
                'description' => 'Pago mensual de un crédito automotriz.',
                'parent_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tarjeta de crédito',
                'description' => 'Pago mensual del saldo de una tarjeta de crédito.',
                'parent_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Préstamo estudiantil',
                'description' => 'Pago recurrente de cuotas de un préstamo estudiantil.',
                'parent_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Seguros
            [
                'name' => 'Seguro médico',
                'description' => 'Pago recurrente del seguro de salud.',
                'parent_id' => 5,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seguro de auto',
                'description' => 'Pago mensual o anual del seguro del vehículo.',
                'parent_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seguro de vida',
                'description' => 'Pago recurrente del seguro de vida.',
                'parent_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seguro de desempleo',
                'description' => 'Pago del seguro en caso de pérdida de empleo.',
                'parent_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seguro de viajes',
                'description' => 'Pago del seguro para protección durante viajes.',
                'parent_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Impuestos y Obligaciones Legales
            [
                'name' => 'Impuesto predial',
                'description' => 'Pago anual del impuesto a la propiedad inmueble.',
                'parent_id' => 6,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Impuesto sobre la renta',
                'description' => 'Pago del impuesto anual sobre ingresos personales o empresariales.',
                'parent_id' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Contribuciones municipales',
                'description' => 'Pagos recurrentes a las municipalidades por servicios locales.',
                'parent_id' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de multas de tránsito',
                'description' => 'Pago de multas por infracciones de tránsito.',
                'parent_id' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Gastos Médicos y de Salud
            [
                'name' => 'Membresía de seguro médico privado',
                'description' => 'Pago recurrente de un seguro médico privado.',
                'parent_id' => 7,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Facturas de hospitales o clínicas',
                'description' => 'Pago de facturas por servicios médicos o tratamientos en hospitales o clínicas.',
                'parent_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tratamientos médicos recurrentes',
                'description' => 'Pagos regulares por tratamientos médicos, como terapias o diálisis.',
                'parent_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medicamentos de uso regular',
                'description' => 'Pago recurrente por medicamentos recetados de uso continuo.',
                'parent_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exámenes médicos periódicos',
                'description' => 'Pagos regulares por chequeos médicos y exámenes preventivos.',
                'parent_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Educación
            [
                'name' => 'Pago de colegiatura',
                'description' => 'Pago mensual de la colegiatura escolar.',
                'parent_id' => 8,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de matrículas',
                'description' => 'Pago único por la matrícula de un curso o institución educativa.',
                'parent_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clases extracurriculares',
                'description' => 'Pagos por clases adicionales, como deportes, arte o música.',
                'parent_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cursos en línea',
                'description' => 'Pagos por cursos de aprendizaje en línea en plataformas educativas.',
                'parent_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Material escolar o universitario',
                'description' => 'Pagos recurrentes para la compra de libros y materiales educativos.',
                'parent_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Programas de certificación profesional',
                'description' => 'Pagos por certificaciones o programas especializados.',
                'parent_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Transporte y Movilidad
            [
                'name' => 'Pago de peajes electrónicos',
                'description' => 'Pago recurrente de peajes electrónicos para el uso de carreteras.',
                'parent_id' => 9, 
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renovación de licencia de conducir',
                'description' => 'Pago para la renovación de la licencia de conducir.',
                'parent_id' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de cuotas de transporte público',
                'description' => 'Pagos recurrentes por el uso de servicios de transporte público.',
                'parent_id' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Servicios de mantenimiento del vehículo',
                'description' => 'Pagos por mantenimiento periódico de vehículos, como cambios de aceite o alineaciones.',
                'parent_id' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de seguro vehicular obligatorio (SOAT)',
                'description' => 'Pago anual del seguro vehicular obligatorio.',
                'parent_id' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de estacionamiento',
                'description' => 'Pagos recurrentes por alquiler de espacios de estacionamiento.',
                'parent_id' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hobbies y Membresías
            [
                'name' => 'Membresía de gimnasio',
                'description' => 'Pago mensual o anual de la membresía a un gimnasio.',
                'parent_id' => 10,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Membresías deportivas (club de golf, tenis, etc.)',
                'description' => 'Pagos recurrentes por membresías a clubes deportivos.',
                'parent_id' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripciones a revistas o periódicos',
                'description' => 'Pagos recurrentes por suscripciones a medios impresos o digitales.',
                'parent_id' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clases de música, arte o idiomas',
                'description' => 'Pagos recurrentes por clases extracurriculares.',
                'parent_id' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripción a plataformas de aprendizaje',
                'description' => 'Pagos recurrentes a plataformas como MasterClass, Duolingo, o similares.',
                'parent_id' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Membresía en clubes recreativos',
                'description' => 'Pagos recurrentes por pertenecer a clubes recreativos o sociales.',
                'parent_id' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Pagos Recurrentes Específicos
            [
                'name' => 'Suscripciones de software (Microsoft 365, Adobe, etc.)',
                'description' => 'Pagos recurrentes por suscripciones de software como Microsoft 365 o Adobe.',
                'parent_id' => 11,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alquiler de equipos o herramientas',
                'description' => 'Pagos recurrentes por el alquiler de equipos o herramientas específicas.',
                'parent_id' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de asistente doméstico',
                'description' => 'Pagos regulares por los servicios de un asistente doméstico.',
                'parent_id' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Servicios de jardinería o limpieza',
                'description' => 'Pagos recurrentes por servicios de mantenimiento de jardín o limpieza del hogar.',
                'parent_id' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suscripciones a herramientas de trabajo colaborativo',
                'description' => 'Pagos recurrentes a herramientas como Slack, Asana o Trello.',
                'parent_id' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Otros Servicios Financieros
            [
                'name' => 'Aportaciones a fondos de ahorro',
                'description' => 'Pagos regulares a fondos de ahorro personales o empresariales.',
                'parent_id' => 12,  
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Inversiones en fondos mutuos',
                'description' => 'Pagos periódicos para inversiones en fondos mutuos.',
                'parent_id' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cuotas sindicales',
                'description' => 'Pagos regulares para cumplir con las cuotas de un sindicato.',
                'parent_id' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pago de deudas a terceros',
                'description' => 'Pagos recurrentes para saldar deudas con personas o instituciones.',
                'parent_id' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aportaciones a planes de pensiones',
                'description' => 'Pagos regulares a planes de pensiones o retiro.',
                'parent_id' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
 
        DB::table('service_entity')->insert(array_merge($categories, $services));
    }
}
